---

services:
  e-lection-api:
    image: 'e-lection:api'
    env_file:
      - '.env'
    build:
      context: '../../'
      dockerfile: 'setup/docker/Dockerfile'
      args:
        CONTRACT_COMPILE_AND_DEPLOY: 'false'
        ADMIN_KEY: ${ADMIN_KEY}
        BUILD_PATH: ${BUILD_PATH}
        CHAIN_RPC: ${CHAIN_RPC}
        CONTRACT_SOURCE_PATH: ${CONTRACT_SOURCE_PATH}
        CONTRACT_ABI_PATH: ${CONTRACT_ABI_PATH}
        CONTRACT_ADDRESS_PATH: ${CONTRACT_ADDRESS_PATH}
        CONTRACT_FILENAME: ${CONTRACT_FILENAME}
        CONTRACT_NAME: ${CONTRACT_NAME}
        PORT: ${PORT}
        IP: 0.0.0.0
    container_name: 'e-lection-api'
    extra_hosts:
      - 'host.docker.internal:host-gateway' # this is needed for blockchain and api server on same server
    ports:
      - '0.0.0.0:<PORT_WHAT_DO_YOU_WANT>:<PORT_AT_ENV_FILE>'
    volumes:
      - './container_data/logs:/app/api/logs'