---

services:
  e-lection-backend:
    image: 'e-lection:backend'
    container_name: 'e-lection-backend'
    env_file:
      - '.env'
    build:
      context: '../../'
      dockerfile: 'setup/docker/Dockerfile'
      args:
        CONTRACT_COMPILE_AND_DEPLOY: 'false'
        BUILD_PATH: ${BUILD_PATH}
    extra_hosts:
      - 'host.docker.internal:host-gateway' # this is needed for blockchain and api server on same server
    ports:
      - '0.0.0.0:<PORT_WHAT_DO_YOU_WANT>:<PORT_AT_ENV_FILE>'
    volumes:
      - './container_data/logs:/app/api/logs'
#      - './container_data/contract:/app/contract/build'